# Generated by Django 2.2 on 2019-04-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tweet_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
