# Generated by Django 2.2 on 2019-05-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_tweet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='lapl_id',
            field=models.IntegerField(null=True),
        ),
    ]
