# Generated by Django 2.2 on 2019-05-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_lapl_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-lapl_id',)},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='pub_date',
        ),
    ]
