# Generated by Django 2.2 on 2019-05-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20190505_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='collection',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='photo',
            name='subcollection',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
