# Generated by Django 2.2 on 2019-05-12 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20190512_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='description',
            new_name='physical_description',
        ),
    ]
