# Generated by Django 2.2.2 on 2019-06-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='faces_extracted',
            field=models.BooleanField(default=False),
        ),
    ]
